name: Deploy to AWS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
    - name: Pack lambda
      run: zip -r deploy/terraform/archive.zip .
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.6
        run: echo "${{ secrets.TERRAFORM_CLOUD_TOKEN }}"
        cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
    - name: Terraform Apply
      env:
        TFE_TOKEN: app.terraform.io=${{ secrets.TERRAFORM_CLOUD_TOKEN }}
      run: terraform init && terraform apply -auto-approve
      working-directory: deploy/terraform
