name: Deploy to AWS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
    - name: Pack lambda
      run: zip -r deploy/terraform/archive.zip .
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.6
    - name: Set environment variables
      env:
        TFE_TOKEN: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: deploy/terraform
